### ISSUE TITLE
Pedido de información sobre product backlog (artefactos de scrum)

### ISSUE THREAD

**Issue by matiasmassuh** [matiasmassuh/JASPER34DW#15]
## Buscar información sobre product backlog (artefactos de scrum)
Uno o dos párrafos de síntesis y el resto desarrollo con información que creas relevante. Valen enlaces, subir archivos, lo que consideres.

Lo pongo en un _sprint de una semana_, como punto inicio. En caso de ser necesario más tiempo, no hay problema. 

**Saludos y gracias de antemano.**

**Comment by stefaniajara** [comment]
**Product Backlog** (pila de producto)
Es uno de los 3 artefactos de Scrum que enlista, ordenadamente, las tareas que se pretenden realizar durante el desarrollo de un proyecto a la vista de todos los integrantes del equipo y es completamente dinámico, ya que va cambiando a medida que al producto se le generen nuevas necesidades para ser competitivo y eficiente.
Este artefacto contiene todas las características, mejoras, funcionalidades que son priorizadas por el _Product Owner_, junto con el equipo, quien además se encarga del contenido y disponibilidad del mismo.

**Comment by stefaniajara** [comment]
[https://muyagile.com/wp-content/uploads/2019/02/Backlog-1-1024x674.png](url)

**Comment by stefaniajara** [comment]
https://muyagile.com/wp-content/uploads/2019/02/Backlog-1-1024x674.png

**Comment by stefaniajara** [comment]
![image](https://user-images.githubusercontent.com/99340983/175130435-2748bc87-f1ef-49ed-8877-a5d841f91db8.png)

**Comment by stefaniajara** [comment]
Todos los ítems que se vayan a incluir en el Product Backlog deben agregar valor, de lo contrario será un desperdicio de tiempo y esfuerzo.
En el Backlog se pueden incluir entradas para explorar necesidades del cliente, analizar _opciones técnicas_, describir _requisitos funcionales y no funcionales_, el trabajo necesario para lanzar el producto y otros ítems de trabajo tales como la _corrección de errores (bugs)_ o la _configuración del entorno_.
Se nos pueden presentar dudas con tareas que no aporten un valor directo a una determinada funcionalidad. Sin embargo, agregarán valor si van a contribuir a aumentar la calidad del código o reducir los errores e incidencias a medio y largo plazo.
