### ISSUE TITLE
Pedido de información sobre issue y proyecto (scrum)

### ISSUE THREAD

**Issue by matiasmassuh** [matiasmassuh/JASPER34DW#17]
## Buscar información sobre issue y proyecto (scrum)
Uno o dos párrafos de síntesis y el resto desarrollo con información que creas relevante. Valen enlaces, subir archivos, lo que consideres.

Lo pongo en un _sprint de una semana_, como punto inicio. En caso de ser necesario más tiempo, no hay problema. 

**Saludos y gracias de antemano.**

**Comment by Marialer27** [comment]
Issues
Un Issue es una nota en un repositorio que trata de llamar la atención sobre un problema. Puede ser un error a corregir, una petición para añadir una nueva opción o característica, una pregunta para aclarar algún tema que no está correctamente aclarado o muchas otras cosas diferentes.
GitHub tiene integrado un gestor de bugs en forma de Issues. Cada Issue representa un problema o mejora del proyecto. Dentro de cada Issue se pueden poner comentarios en los que informar de los progresos o debatir la mejor forma de solucionarla.
Para poner una nueva Issue, podemos hacer click en "New Issue", tras lo cual nos aparece el siguiente formulario para rellenar. Desde él podemos añadir un título, una descripción, asignar la Issue a una persona concreta (o varias) y etiquetar la Issue.
![elements_issues](https://user-images.githubusercontent.com/87164629/175754475-a97cc016-5d50-4e89-8502-d76664ea5b59.png)


Projects
Un Project de GitHub es una forma de organizar tareas e Issues relacionadas entre sí. Está inspirada en el método Kanban y tiene un aspecto muy similar al de los tablones de Trello. A cada Project le podremos añadir tarjetas que pueden corresponder o no con Issues del proyecto y moverlas entre las distintas columnas del tablón.
![elements_project](https://user-images.githubusercontent.com/87164629/175754488-dc520bd9-a34b-4f1b-afab-339ab21c6fac.png)
