### ISSUE TITLE
Leer material sobre Github y Scrum

### ISSUE THREAD

**Issue by matiasmassuh** [matiasmassuh/JASPER34DW#2]

**Comment by MaxiCantarino** [comment]
Probando

**Comment by matiasmassuh** [comment]
> Probando

Funciona desde el celular esto.
![IMG-20220616-WA0037](https://user-images.githubusercontent.com/106634033/174190127-9bf0d277-4273-4c4a-bce0-ed7b9f4b6667.jpg)

**Comment by Monimo1** [comment]
Concepto de sprint backlog y de increment artefactos de scrum

	El Sprint Backlog es la suma de el Objetivo del Sprint, los elementos del Product Backlog elegidos para el Sprint, más un plan de acción de cómo crear el Incremento de Producto.
•	Es uno de los 3 artefactos de Scrum y se construye durante el evento del Sprint Planning. Es un plan realizado por y para los Developers. 
•	El equipo generalmente divide el trabajo en elementos llamados Sprint Backlog Ítems (SBI). Estos elementos pueden representar tareas que el equipo debe completar, bloques de construcción intermedios que se combinan en una entrega, o cualquier otra unidad de trabajo que ayude al equipo a comprender cómo lograr el Sprint Goal dentro del Sprint.
•	Es importante que el Sprint Backlog esté visible para todo el equipo, ya que tiene como objetivo proporcionar transparencia sobre el estado del trabajo planificado para el Sprint. Es por esta razón que me gusta llamarlo un radiador de información.
•	Ejemplo de Sprint Backlog: tablero Kanban.
El Sprint Backlog es un artefacto que pretende ser una imagen muy visible y en tiempo real del trabajo que los Developers planean realizar durante el Sprint para lograr el Objetivo del Sprint. Esto fomenta el pilar de Scrum de la transparencia.

	El Increment (“Incremento” en español) o también conocido como Incremento de Producto es la suma de todos los ítems del Product Backlog (PBIs) completados durante un Sprint y el valor de los incrementos de todos los Sprints pasados. Es uno de los 3 artefactos de Scrum y se presenta en cada Sprint Review.
•	Como todos los artefactos en Scrum, el Increment también contienen un compromiso asociado. El compromiso del Increment es el Definition of Done.
•	El Definition of Done «DoD» (o “Definición de terminado” en español) es una descripción formal del estado del Increment cuando cumple con las medidas de calidad requeridas para el producto.
En el momento en que un elemento del Product Backlog cumple con la Definición de Terminado, nace un Increment. La Definición de Terminado pretende crear transparencia al brindar a todos un entendimiento compartido de qué trabajo se completó como parte del Increment.

**Comment by DianaCormick** [comment]
![SCRUM](https://user-images.githubusercontent.com/106692455/175796519-46a28c29-8f3c-4f84-a802-dd4172ed8d58.png)
