### ISSUE TITLE
Zoom con los integrantes para primer contacto "cara a cara"

### ISSUE THREAD

**Issue by matiasmassuh** [matiasmassuh/JASPER34DW#3]
Conocer los conocimientos de cada integrante, para saber en que tienen más facilidad.  Reunión en Zoom planeada para sábado 17 a las 15 hs.

**Comment by ChRi5714n** [comment]
Escribo algo para saber que pasa si pongo algo acá! JAJA!

**Comment by matiasmassuh** [comment]
> Escribo algo para saber que pasa si pongo algo acá! JAJA!

Si si, funciona. Y de paso, probé de entrar con el celular. Va bien!

**Comment by ChRi5714n** [comment]
Bueno! Hoy vi lo de Github y mas o menos lo que nos piden para el proyecto y los Sprint. Es parecido a lo que hice el año pasado con mi emprendimiento, así que lo pude entender. Me pareció sencillo.
Nos vemos hoy a las 15hs!

**Comment by stefaniajara** [comment]
Buenas buenas, viendo cómo nos vamos armando

**Comment by nadgis** [comment]
Hola grupo...investigando y familiarizándome con nuestra OFICINA....
