### ISSUE TITLE
Pedido de definición de SCRUM

### ISSUE THREAD

**Issue by matiasmassuh** [matiasmassuh/JASPER34DW#4]
Por favor, pone en un comentario o archivo, información que encuentres de SCRUM.

**Comment by DianaCormick** [comment]
Scrum es un marco que permite el trabajo colaborativo entre equipos. Scrum anima a los equipos a aprender a través de las experiencias, a autoorganizarse mientras aborda un problema y a reflexionar sobre lo que se va logrando y lo que no, para mejorar continuamente.
Aunque suele considerarse un marco de gestión de proyectos ágil, scrum incluye un conjunto de reuniones, herramientas y funciones que, de forma coordinada, ayudan a los equipos a estructurar y gestionar su trabajo.

**Comment by matiasmassuh** [comment]
> Scrum es un marco que permite el trabajo colaborativo entre equipos. Scrum anima a los equipos a aprender a través de las experiencias, a autoorganizarse mientras aborda un problema y a reflexionar sobre lo que se va logrando y lo que no, para mejorar continuamente. Aunque suele considerarse un marco de gestión de proyectos ágil, scrum incluye un conjunto de reuniones, herramientas y funciones que, de forma coordinada, ayudan a los equipos a estructurar y gestionar su trabajo.

![200](https://user-images.githubusercontent.com/106634033/174191934-8075d492-1379-47f8-b449-cbfbaa54089b.gif)

**Comment by ChRi5714n** [comment]
Scrum es una de las metodologías ágiles más populares. Es una metodología de adaptación, **iterativa**,
rápida, flexible y eficaz, diseñada para ofrecer un valor significativo de forma rápida en todo el proyecto.

Una fortaleza clave de Scrum radica en el uso de equipos multi-funcionales, auto-organizados y con poder,
que dividen su trabajo en ciclos de trabajo cortos y concentrados llamados Sprints

Scrum requiere un Scrum Master para fomentar un entorno donde:

> 1. Un propietario del producto (Product Owner) ordena el trabajo de un problema complejo en un Product Backlog.
> 2. El equipo de Scrum convierte una selección del trabajo en un Incremento de valor durante un Sprint.
> 3. El equipo de Scrum y sus partes interesadas (stakeholders) inspeccionan los resultados y realizan los ajustes necesarios para el próximo Sprint.
> 4. Repetir

El ciclo de Scrum comienza con un Stakeholder Meeting, durante el cual se crea la visión del proyecto. El _Product Owner_, entonces desarrolla un _Producto Backlog_  que contiene una lista priorizada de los requerimientos del proyecto. 
Cada Sprint comienza con un Reunión de Planificación del Sprint durante el cual se dan prioridad a las actividades. Un Sprint suele durar entre una y seis semanas en el cual el Equipo Scrum trabaja en la creación Entregables (Deliverables) potencialmente listos para implementar en el proyecto.

FUENTES: 

[https://www.tenstep.ec/portal/images/pdfs/Suscripciones_TenStep/Silver/SCRUMstudy_GUIA_SBOK_espanol.pdf](url)

[https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-Spanish-European.pdf](url)
