### ISSUE TITLE
Pedido de información sobre concepto de sprint review meeting y sprint retrospective (ceremonias de scrum)

### ISSUE THREAD

**Issue by matiasmassuh** [matiasmassuh/JASPER34DW#9]
Buscar información sobre sprint review meeting y sprint retrospective (ceremonias de scrum)
Uno o dos párrafos de síntesis y el resto desarrollo con información que creas relevante. Valen enlaces, subir archivos, lo que consideres.

Lo pongo en un sprint de una semana, como punto inicio. En caso de ser necesario más tiempo, no hay problema. Saludos y gracias de antemano.

**Comment by hernan04** [comment]
Sprint Review Meeting y Sprint Retrospective
¿Qué son y en qué se diferencian?

Sprint Review Meeting
En Scrum, cada sprint debe generar una mejora notable sobre el producto en desarrollo. Esto significa que al final de cada sprint, el equipo ha producido un software que ha sido codificado, testeado y que por tanto es usable (parcialmente).

Así, al final de cada sprint, se lleva a cabo una reunión conocida como sprint review meeting. Durante esta reunión, el equipo de Scrum muestra lo que se ha logrado realizar. Por lo general, esto se corresponde con una demo que incuye las nuevas características.

La sprint review meeting se realiza de manera informal, por lo general evitando el uso de presentaciones en PowerPoint y con un tiempo de preparación menor a 2 horas (antes de iniciar). Esta reunión no debe convertirse en una distracción o un desvío significativo para el equipo; más bien, debe ser el resultado natural del sprint.

Generalmente los participantes que intervinen en esta reunión son el product owner, el equipo de desarrollo, el ScrumMaster, administración, clientes y desarrolladores de otros proyectos.

Durante la revisión del sprint, el proyecto es evaluado en función al sprint goal, que se determinó durante el Sprint Planning Meeting. Lo ideal es que el equipo haya completado los items que fueron seleccionados del product backlog para ser considerados en el sprint, pero es más importante alcanzar el objetivo general del sprint (sprint goal).

Sprint Retrospective
No importa qué tan bueno sea el equipo de Scrum, siempre hay una oportunidad de mejora. Aunque un equipo de Scrum siempre está buscando oportunidades de mejora, el equipo debe asignar un momento especial para ello, es decir, un periodo al final de cada sprint para reflexionar acerca de lo que están haciendo y encontrar formas de mejorar. Esto se conoce como la retrospectiva de sprint (sprint retrospective).

La sprint retrospective es usualmente la última cosa que se hace en un sprint. Muchos equipos llevarán a cabo esta restrospectiva justo después de la sprint review (revisión de sprint). Todo el equipo, incluyendo al ScrumMaster y el product owner deben participar. Podemos programar esta retrospectiva con una duración de una hora, que generalmente es suficiente. Sin embargo, ocasionalmente podría surgir un tema candente o un conflicto en el equipo, lo que hará que la retrospectiva lleve más tiempo.

Aunque hay muchas formas de realizar una retrospectiva ágil, lo más recomendable es llevar a cabo esta reunión de una forma inicia-para-continua. Esta es tal vez la forma más simple, pero generalmente la más efectiva para conducir una retrospectiva. Este enfoque sugiere preguntar a cada miembro del equipo, para que identifique temas específicos que son relevantes para el equipo:

Empezar a identificar asuntos importantes
Dejar de hacerlo
Continuar con ello
Hay muchas variantes de este formato. El ScrumMaster puede facilitar esta reunión solicitando que cada uno lance ideas de forma ordenada. El ScrumMaster puede ir dando vueltas, solicitando a cada persona que comente sobre un tema que le parezca importante para iniciar la discusión, pedirle que se detenga o continúe. Por ejemplo, él o ella puede decir a todos que se centren en un tema en particular, o pedir que no se hable más de cierto tema, porque se han descuidado otros.

Luego de la lluvia de ideas inicial, los equipos suelen votar de forma específica por los items que creen que se deberían considerar para el sprint que está por iniciar. Al final del sprint, la siguiente retrospectiva suele iniciar consultando la lista de items seleccionados en la retrospectiva anterior.

**Comment by hernan04** [comment]
Se posee recursos de video sobre el mismo, se considera pertinente su anexo. Comentar para su reenvio o archivo final
